//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeduShop.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string ValueString { get; set; }
        public Nullable<int> ValueInt { get; set; }
    }
}
